### PR TITLE
Added feature to maintain a list of favorite named settings.

### PR DESCRIPTION
**Pull request by makermusings**
This features adds named settings (favorites) which allow you to associate a feedrate/intensity pair with a name you enter and then select it by choosing the name from a dropdown menu when defining your passes. The goal is to let you develop your own library of the settings you use for each of the materials you use without having to remember them or record them elsewhere.

You access the list of favorites from the new star menu in the pass definitions or through the Favorites entry in the hamburger menu.

### CODE REVIEW

**Comment by scottshambaugh** [comment]
Thanks! A few things I noticed here:
1) Unclear how to add a new favorite? Star > New Favorite... shows an empty menu (pcitured)
image
2) The pxsize on the first pass no longer pick up the default, and instead shows NaN or Undefined. Also, glancing through the source, could you include pxsize as part of the data included in a favorite?
3) I kind of like 'presets' as a name rather than 'favorites', but you're doing the work so I'll leave it up to you.

**Comment by makermusings** [comment]
Thanks for testing! Of course, it all works fine for me.

1. Here's what the New Favorite... is supposed to look like:
new_favorite_screenshot

Would you mind grabbing some debug information for me? Assuming you're on Chrome, open developer tools with F12, click to show the Console tab in the developer tools area, then click the star -> New Favorite.... Grab any error messages in the console and pass them along. Holler if this isn't clear.

2. I'll see if I can reproduce or diagnose the NaN problem for pxsize. I'll definitely add it as part of the data; great idea.

3. Presets is a much better name than favorites. Once I get these bugs ironed out, I'll update the PR with the name changed everywhere.

**Comment by scottshambaugh** [comment]
Looks like not being able to add a favorite was just an issue of my cache not being cleared, a force reload of the interface fixed that issue and favorites are saving and loading as expected now.

**Comment by scottshambaugh** [comment]
Also, it looks like the pxsize being undefined only shows up on library items that already have settings associated with them (like the default Lasersaur vector graphic). Doesn't seem to be an issue loading other svg files.

**Comment by makermusings** [comment]
Changes:

1. Renamed to "Presets" instead of "Favorites".
2. Include pxsize with the other data for a preset.

The presets are stored in ~/.driveboardapp/presets.json and the old favorites.json, if any, is now just ignored. If you have useful favorites already, you can refer to favorites.json and enter them as new presets.

**Comment by scottshambaugh** [comment]
Tested this out, seems to be working well! Only thing I found is that if I load a file from the Library (such as the lasersaur test pattern), the pxsize is undefined at the start. This is pretty minor though, I'm happy to merge in the meantime.
image

**Comment by scottshambaugh** [comment]
I looked again and it seems that pxsize being undefined was present before your changes, so I'd consider it outside the needed scope of this PR. Merged!

**Comment by makermusings** [comment]
I thought the pxsize problem might be unrelated, but I was going to look into it anyway. I'll send along a new PR if I track it down.

**Comment by scottshambaugh** [comment]
FYI, I fixed a bug not being able to delete presets here: https://github.com/scottshambaugh/driveboardapp/commit/4e82a8d57967f4776dbfe76402330f13f0abcbcc
And the pxsize being undefined I fixed here: https://github.com/scottshambaugh/driveboardapp/commit/3ac02b8ebd5aad69daa49d060860875d26e8e18a

**Pull request merged**
